spring.application.name=AboutMe-API

# Server Configuration
server.port=8080

# User Profile Configuration
user.profile.email=${USER_EMAIL:danieleakinola@gmail.com}
user.profile.name=${USER_NAME:Akinola Daniel}
user.profile.stack=${USER_STACK:Spring Boot/Java}

# External API Configuration
catfact.api.url=https://catfact.ninja/fact

# Logging Configuration
logging.level.root=INFO
logging.level.dev.slethware.aboutme=DEBUG
logging.file.name=logs/aboutme-api.log